### ISSUE TITLE
Access Token: Not found

### ISSUE THREAD

**Issue by onion0835** [yi-ge/chatgpt-api#1]
[OpenAI][8][CRITICAL] Access Token: Not found Auth0 did not issue an access token.
[OpenAI][9] Attempting to get access token from: https://chat.openai.com/api/auth/session
[OpenAI][9] Access Token: Not found, Please try again with a proxy (or use a new proxy if you are using one)
>> Failed to create access token.
how to solve this?

**Comment by onion0835** [comment]
我是用的香港服务器，也不行么？

**Comment by yi-ge** [comment]
香港不在支持的地区列表中
