### ISSUE TITLE
No module named 'PyChatGPT.src'

### ISSUE THREAD

**Issue by ludashi2020** [yi-ge/chatgpt-api#3]
[root@dbci chatgpt-api]# python3 main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from PyChatGPT.src.pychatgpt import Chat, Options
ModuleNotFoundError: No module named 'PyChatGPT.src'
[root@dbci chatgpt-api]# python3 -V
Python 3.7.8

**Comment by yi-ge** [comment]
请克隆下子模块
